### ISSUE TITLE
Avoid hardcoding dependencies

### ISSUE THREAD

**Issue by BenWestgate** [bowlarbear/arctica#63]
In https://github.com/bowlarbear/arctica/blob/8b80a9e792b6ba3f4d84f327ec714272ac5c9d34/src/init.rs#L199C1-L199C123

I noticed the name and version number of all dependencies is hard coded, this requires you manually pushing updates whenever your upstream does.

This can cause delays in new arctica installs receiving important security updates for their dependencies.

You would simplify your life to have a file with a list of dependencies and their minimum versions and let the script iterate over it and fetch the latest minor version (major versions you may still want to manually push as they can break backwards compatibility), same for when you are copying them to the backup USB sticks.

**Comment by bowlarbear** [comment]
duplicate
https://github.com/bowlarbear/arctica/issues/35
